version: "3.9"

volumes:
  php-fpm-socket:
    name: recoursion-coding-enviroment-for-php_php-fpm-socket

services:

  app:
    container_name: recoursion-coding-enviroment-for-php-backend
    build:
      context: ./php
      dockerfile: ./Dockerfile
    image: recoursion-coding-enviroment-for-php-backend:1.0
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/workspace:cached
