version: "3.9"

networks:
  external-api-net:
    name: recoursion-backend-project-external-api
    external: true
      
volumes:
  php-fpm-socket:
    name: recoursion-backend-project-for-php_php-fpm-socket

services:

  app:
    container_name: recoursion-backend-project-for-php
    build:
      context: ./php
      dockerfile: ./Dockerfile
    image: recoursion-backend-project-for-php:1.0
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/workspace:cached
    networks:
      external-api-net:
        ipv4_address: 192.168.1.3
